### ISSUE TITLE
Error: Cannot process this XML structure: {xml_root.tag}

### ISSUE THREAD

**Issue by linden-yuan** [So-Cool/myslideslive#10]
mySlidesLive can't download slides from 2022 and later, it seems. When I run `msl --slide 2 3 https://slideslive.com/38988636/24-sparsity-on-gpu-tensor-cores`, no download occurs and I get the following output:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/msl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/myslideslive/cli.py", line 83, in main
    msl = SlidesLive(url)
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/myslideslive/slideslive.py", line 556, in __init__
    meta = get_slide_metadata(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/myslideslive/slideslive.py", line 153, in get_slide_metadata
    meta_data_ = parse_slide_xml(meta_content)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/myslideslive/slideslive.py", line 118, in parse_slide_xml
    raise RuntimeError(f'Cannot process this XML structure: {xml_root.tag}.')
RuntimeError: Cannot process this XML structure: Error.
```

The presentation https://slideslive.com/39004359/optimal-transport-in-learning-control-and-dynamical-systems also yields the same issue.

**Comment by So-Cool** [comment]
Thanks, @linden-yuan. The new release (`0.6`) should fix this issue.
