### ISSUE TITLE
KeyError: 'image'

### ISSUE THREAD

**Issue by BleedingDev** [So-Cool/myslideslive#14]
I am trying to download this video URL: https://slideslive.com/39007973/zahajeni-digisemestru

But I get error:
```powershell
Traceback (most recent call last):
  File "D:\Videos\DigiSemestr\download_slides.py", line 4, in <module>
    msl.download_slides(slide=(1, 43))
  File "D:\Videos\DigiSemestr\digisemestr\Lib\site-packages\myslideslive\slideslive.py", line 634, in download_slides
    url_list = self.get_slide_urls(slide_type=slide_type,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Videos\DigiSemestr\digisemestr\Lib\site-packages\myslideslive\slideslive.py", line 622, in get_slide_urls
    return get_urls(self.video_id, self.video_metadata,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Videos\DigiSemestr\digisemestr\Lib\site-packages\myslideslive\slideslive.py", line 222, in get_urls
    slide_id=s['image']['name'],
             ~^^^^^^^^^
KeyError: 'image'
```

**Comment by So-Cool** [comment]
Thanks for reporting the bug. This has to do with the presentation having embedded some short videos, e.g., slide 18. Release 0.7 includes a workaround that replaces these videos with static images. Issue #16 documents this problem (which will eventually be addressed).

**Comment by BleedingDev** [comment]
Thank you for reply. :)
