### ISSUE TITLE
"JSON Decode" error

### ISSUE THREAD

**Issue by linden-yuan** [So-Cool/myslideslive#3]
Hi,

I'm having trouble running this code. When in terminal I run e.g.

> msl --slide 1074 1075 \
> https://slideslive.com/38956531/beyond-static-papers-rethinking-how-we-share-scientific-understanding-in-ml

, the slides don't download and I get the following error message:

Traceback (most recent call last):
  File "/Users/yuan/opt/anaconda3/bin/msl", line 8, in <module>
    sys.exit(main())
  File "/Users/yuan/opt/anaconda3/lib/python3.8/site-packages/myslideslive/cli.py", line 83, in main
    msl = SlidesLive(url)
  File "/Users/yuan/opt/anaconda3/lib/python3.8/site-packages/myslideslive/slideslive.py", line 500, in __init__
    self.video_description = get_sl_info(self.video_id)
  File "/Users/yuan/opt/anaconda3/lib/python3.8/site-packages/myslideslive/slideslive.py", line 69, in get_sl_info
    info_json = json.loads(info_request.content.decode())
  File "/Users/yuan/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/yuan/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/yuan/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by So-Cool** [comment]
@linden-yuan, version 0.3 fixes this issue (`pip install myslideslive==0.3`).
